/**
 * Generated by orval v6.5.1 🍺
 * Do not edit manually.
 * Plutus.Api
 * OpenAPI spec version: v1
 */
import {
  rest
} from 'msw'
import faker from 'faker'

export const getGetTransactionsMock = () => ([...Array(faker.datatype.number({min: 1, max: 10}))].map(() => ({id: faker.random.word(), amount: faker.datatype.number()})))

export const getCreateTransactionMock = () => ({id: faker.random.word(), amount: faker.datatype.number()})

export const getTransactionMSW = () => [
rest.get('*/api/accounts/:accountId/transactions', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetTransactionsMock()),
        )
      }),rest.post('*/api/accounts/:accountId/transactions', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getCreateTransactionMock()),
        )
      }),]
