/**
 * Generated by orval v6.5.1 🍺
 * Do not edit manually.
 * Plutus.Api
 * OpenAPI spec version: v1
 */

export interface AccountResponse {
  id?: string;
  title?: string | null;
  description?: string | null;
  balance?: number;
}
