/**
 * Generated by orval v6.5.1 🍺
 * Do not edit manually.
 * Plutus.Api
 * OpenAPI spec version: v1
 */

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface TransactionResponse {}
