/**
 * Generated by orval v6.5.1 🍺
 * Do not edit manually.
 * Plutus.Api
 * OpenAPI spec version: v1
 */

export interface UserResponse {
  userName?: string | null;
  email?: string | null;
  roles?: string[] | null;
  token?: string | null;
}
